stages:
  - setup

Connect:
  image: jonsy13/k3d
  stage: setup
  tags:
    - litmus-portal-2
  script:
    - k3d cluster create litmus
    - kubectl get pods
  artifacts:
    when: always
    paths:
      - .kube/