image: docker:stable
variables:
  KUBECTL: v1.17.0
  KIND: v0.8.1
services:
  - docker:dind
stages:
  - setup
  # - test
test:
  stage: setup
  script:
    - apk add -U wget
    - wget -O /usr/local/bin/kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND}/kind-linux-amd64
    - chmod +x /usr/local/bin/kind
    - wget -O /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBECTL}/bin/linux/amd64/kubectl
    - chmod +x /usr/local/bin/kubectl
    - kind create cluster --config=./gitlab/kind-config.yaml
    - sed -i -E -e 's/localhost|0\.0\.0\.0/docker/g' "$HOME/.kube/config"
    - chmod 755 ./copyKube.sh
    - ./copyKube.sh
  artifacts:
    when: always
    paths:
      - .kube/

# test:
#   stage: test
#   script:
#     - apk add -U wget
#     - wget -O /usr/local/bin/kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND}/kind-linux-amd64
#     - chmod +x /usr/local/bin/kind
#     - wget -O /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBECTL}/bin/linux/amd64/kubectl
#     - chmod +x /usr/local/bin/kubectl
#     - chmod 755 ./copyKube.sh
#     - ./copyKube.sh
